/* Project copy keeps professional, independent and studio work distinct. */
const portfolio = [
  {id:'jts',category:'digital',stage:'active',featured:true,theme:'systems',
    title:['JTS operations platform','منصة JTS لإدارة العمليات'],brand:'JTS',status:['In development','قيد التطوير'],
    line:['One connected operation.','عمليات مترابطة. في مكان واحد.'],
    role:['Studio Irth / Business analysis & application development','استوديو إرث / تحليل الأعمال وتطوير التطبيقات'],
    description:['An operations platform in development for engineering and technical services: connecting client enquiries, quotations, projects, technical reports and finance.','منصة قيد التطوير لخدمات الهندسة والخدمات الفنية، تربط استفسارات العملاء وعروض الأسعار بالمشاريع والتقارير الفنية والإدارة المالية.'],
    detail:['The work starts with the way the team actually operates. Its scope includes technician assignments, report reviews and corrections, equipment records, invoices and employee workflows. The platform is being refined through an active development backlog.','يبدأ العمل بفهم طريقة عمل الفريق. يشمل النطاق توزيع مهام الفنيين، ومراجعة التقارير وتصحيحها، وسجلات المعدات، والفواتير، وإجراءات الموظفين. يجري تطوير المنصة وتحسينها وفق قائمة متطلبات مستمرة.'],
    tags:[['Process mapping','Connected workflows','Business applications'],['تحليل العمليات','ربط مسارات العمل','تطبيقات الأعمال']]},
  {id:'water',category:'creative',stage:'completed',featured:true,theme:'water',
    title:['UNICEF · Water campaign','يونيسف · حملة المياه'],brand:['Every drop.\nA bigger story.','كل قطرة.\nوراءها حكاية.'],status:['Completed','مكتمل'],
    line:['6 reels / Water in Jordan','٦ ريلز / المياه في الأردن'],
    role:['UNICEF / Campaign content & short-form storytelling','يونيسف / محتوى الحملات والسرد بالفيديو القصير'],
    description:['Six reels about water in Jordan, bringing a vital public issue into an everyday, social-first format.','ستة فيديوهات ريلز عن المياه في الأردن، تقرّب قضية حيوية من الناس بصيغة تناسب منصات التواصل.'],
    detail:['A campaign contribution centred on short-form video: making room for an important topic in the way people watch, share and discover stories. Part of Nabil’s communications experience with UNICEF.','مساهمة في الحملة من خلال الفيديو القصير، لفتح مساحة لقضية مهمة ضمن طريقة مشاهدة الناس للحكايات واكتشافها ومشاركتها. من تجربة نبيل في التواصل مع اليونيسف.'],
    tags:[['6 reels','Water awareness','Jordan'],['٦ ريلز','التوعية بالمياه','الأردن']]},
  {id:'mental',category:'creative',stage:'completed',featured:true,theme:'mental',
    title:['UNICEF · Mental health campaign','يونيسف · حملة الصحة النفسية'],brand:['Let’s talk.\nLet’s understand.','نحكي.\nونفهم أكثر.'],status:['Completed','مكتمل'],
    line:['10 reels / Mental health awareness','١٠ ريلز / التوعية بالصحة النفسية'],
    role:['UNICEF / Awareness content & toolkit communication','يونيسف / محتوى توعوي والتعريف بأدوات الصحة النفسية'],
    description:['Ten reels created with UNICEF to raise mental health awareness and introduce its mental health toolkit.','عشرة فيديوهات ريلز مع اليونيسف للتوعية بالصحة النفسية والتعريف بحقيبة أدوات الصحة النفسية.'],
    detail:['The communication task: bring awareness and a practical resource into the same conversation. Short-form content gives the subject an accessible entry point and introduces audiences to the toolkit.','المهمة الاتصالية: جمع التوعية والمورد العملي في حوار واحد. يمنح المحتوى القصير الجمهور مدخلًا قريبًا إلى الموضوع، ويعرّفه بحقيبة الأدوات.'],
    tags:[['10 reels','Awareness campaign','Mental health toolkit'],['١٠ ريلز','حملة توعوية','أدوات الصحة النفسية']]},
  {id:'brainy',category:'creative',stage:'completed',featured:true,theme:'brainy',
    title:['Brainy Nation × ADHDJO','Brainy Nation × ADHDJO'],brand:['Different minds.\nShared understanding.','عقول مختلفة.\nوفهم يجمعنا.'],status:['Completed','مكتمل'],
    line:['ADHD Awareness Month','شهر التوعية باضطراب فرط الحركة وتشتّت الانتباه'],
    role:['ADHDJO / Campaign collaboration','ADHDJO / تعاون في حملة توعوية'],
    description:['A month-long Instagram campaign bringing together specialists, parents and people with ADHD to challenge stigma and share different perspectives.','حملة على إنستغرام استمرت شهرًا، جمعت مختصين وأهالي وأشخاصًا لديهم ADHD لمواجهة الوصمة ومشاركة وجهات نظر مختلفة.'],
    detail:['A collaboration with Brainy Nation, connecting professional perspectives with lived experience through ADHDJO.','تعاون مع Brainy Nation يربط وجهات النظر المتخصصة بالتجربة الشخصية من خلال ADHDJO.'],
    tags:[['Campaign collaboration','Multiple perspectives','ADHD awareness'],['تعاون إبداعي','تعدد وجهات النظر','التوعية بـ ADHD']],
    url:'https://ae.linkedin.com/posts/brainynation_october-was-adhd-awareness-month-and-at-activity-7391775371123404800-ubUr',link:['View the campaign recap','شاهد ملخّص الحملة']},
  {id:'leave',category:'digital',stage:'completed',title:['Non-staff leave application','تطبيق إجازات العاملين غير الموظفين'],status:['Delivered','تم تنفيذه'],
    role:['UNICEF / Power Platform development','يونيسف / تطوير باستخدام Power Platform'],
    description:['A leave-management application built within Nabil’s UNICEF role. It digitized a recurring administrative workflow and was used for more than three years.','تطبيق لإدارة الإجازات طوّره نبيل ضمن عمله في اليونيسف. حوّل إجراءً إداريًا متكررًا إلى مسار رقمي، واستُخدم لأكثر من ثلاث سنوات.'],
    tags:[['Microsoft Power Platform','Workflow digitization','3+ years in use'],['Microsoft Power Platform','رقمنة الإجراءات','أكثر من ٣ سنوات من الاستخدام']]},
  {id:'rentfleet',category:'digital',stage:'completed',title:['RentFleet','RentFleet'],status:['Built','تم تطويره'],
    role:['Business system / Design & development','نظام أعمال / التصميم والتطوير'],
    description:['A car-rental tracking and management system that brings operational information into a structured workflow, with everyday usability at its centre.','نظام لتتبّع وإدارة تأجير السيارات، يجمع معلومات العمليات ضمن مسار واضح، ويضع سهولة الاستخدام اليومي في صميم التصميم.'],
    tags:[['Rental operations','Tracking','Business applications'],['عمليات التأجير','التتبّع','تطبيقات الأعمال']]},
  {id:'meraki',category:'digital',stage:'archive',title:['Connected learning centres · Meraki','مراكز تعلّم متصلة · Meraki'],status:['Professional experience','خبرة مهنية'],
    role:['UNICEF-supported centres / Network & content control','مراكز مدعومة من اليونيسف / إدارة الشبكات والمحتوى'],
    description:['Network and content-control work using Cisco Meraki across UNICEF-supported centres, drawing on approximately eight years of experience with the environment.','عمل على الشبكات والتحكم بالمحتوى باستخدام Cisco Meraki في مراكز مدعومة من اليونيسف، بخبرة امتدت نحو ثماني سنوات في هذه البيئة.'],
    tags:[['Cisco Meraki','Connectivity','Content controls'],['Cisco Meraki','الاتصال','إدارة الوصول للمحتوى']]},
  {id:'mdm',category:'digital',stage:'completed',title:['Learning at scale · Tablet management','التعلّم على نطاق واسع · إدارة الأجهزة اللوحية'],status:['Delivered deployment','تم تنفيذ النشر'],
    role:['Professional experience / Mobile device management','خبرة مهنية / إدارة الأجهزة المحمولة'],
    description:['Mobile device management supporting approximately 25,000 tablets for protected e-learning during and after the COVID-19 period. A large-scale digital operations contribution in a humanitarian setting.','إدارة أجهزة محمولة لدعم نحو ٢٥ ألف جهاز لوحي للتعلّم الإلكتروني المحمي خلال فترة كوفيد-١٩ وما بعدها، ضمن تجربة تشغيل رقمي واسعة النطاق في المجال الإنساني.'],
    tags:[['~25,000 tablets','MDM','Digital learning'],['نحو ٢٥ ألف جهاز','إدارة الأجهزة','التعلّم الرقمي']]},
  {id:'adhdjoweb',category:'digital',stage:'active',title:['ADHDJO · Community website','ADHDJO · موقع المجتمع'],status:['Prototype','نموذج أولي'],
    role:['Independent project / Website design & prototyping','مشروع مستقل / تصميم الموقع والنماذج الأولية'],
    description:['A website prototype for the ADHDJO community, bringing educational content, resources and a proposed specialist directory into one place. The directory remains a prototype feature.','نموذج أولي لموقع مجتمع ADHDJO، يجمع المحتوى التوعوي والمصادر ودليلًا مقترحًا للمختصين في مكان واحد. الدليل جزء من النموذج الأولي.'],
    tags:[['Community platform','Content design','Prototype'],['منصة مجتمعية','تصميم المحتوى','نموذج أولي']]},
  {id:'nabz',category:'digital',stage:'exploration',title:['NABZ · Personal command centre','NABZ · مساحة إدارة اليوم'],status:['Prototype exploration','استكشاف ونموذج أولي'],
    role:['Independent product / Concept & prototyping','منتج مستقل / الفكرة والنمذجة'],
    description:['An exploration of a personal workspace for tasks, calendar planning and capturing scattered thoughts. A product idea being shaped around how attention and everyday life actually work.','استكشاف لمساحة شخصية تجمع المهام وتخطيط الوقت والتقاط الأفكار المتفرقة. فكرة منتج تنطلق من الطريقة التي يعمل بها الانتباه وتفاصيل الحياة اليومية.'],
    tags:[['Product thinking','Task organisation','Prototyping'],['تطوير أفكار المنتجات','تنظيم المهام','النمذجة']]},
  {id:'blutactical',category:'creative',stage:'archive',title:['BluTactical','BluTactical'],status:['Campaign collaboration','تعاون في حملة'],
    role:['Campaign & podcast work','أعمال حملات وبودكاست'],
    description:['Creative work with BluTactical across campaign and podcast collaboration, part of Nabil’s wider communications portfolio.','أعمال إبداعية مع BluTactical تشمل التعاون في الحملات والبودكاست، ضمن تجربة نبيل الأوسع في التواصل وصناعة المحتوى.'],
    tags:[['Creative communications','Campaigns','Podcast'],['التواصل الإبداعي','الحملات','البودكاست']]},
  {id:'adhdjo',category:'creative',stage:'active',title:['ADHDJO · An ongoing conversation','ADHDJO · حوار مستمر'],status:['Ongoing','مستمر'],
    role:['Founder & content creator','تأسيس وصناعة محتوى'],
    description:['An Arabic-first platform for stories and conversations around ADHD and neurodiversity. Lived experience meets storytelling to make complex topics more relatable to audiences in the region.','منصة عربية للحكايات والحوارات حول اضطراب فرط الحركة وتشتّت الانتباه والتنوع العصبي. تجمع التجربة الشخصية بصناعة المحتوى لتقريب الموضوعات المعقدة من جمهور المنطقة.'],
    tags:[['Community building','Arabic storytelling','On-camera content'],['بناء المجتمع','السرد بالعربية','محتوى أمام الكاميرا']],
    url:'https://www.instagram.com/adhdjo/',link:['Explore ADHDJO','اكتشف ADHDJO']},
  {id:'afaqcast',category:'creative',stage:'archive',title:['AfaqCast · Youth voices','AfaqCast · أصوات الشباب'],status:['Professional experience','خبرة مهنية'],
    role:['Zaatari / Youth podcast & studio support','الزعتري / دعم بودكاست الشباب والاستوديو'],
    description:['Support for youth podcast and studio activity in Zaatari, connecting production tools, creative practice and opportunities for young people to tell their own stories.','دعم أنشطة بودكاست الشباب والاستوديو في الزعتري، لربط أدوات الإنتاج والممارسة الإبداعية بفرص يروي من خلالها الشباب حكاياتهم بأنفسهم.'],
    tags:[['Podcast production support','Youth engagement','Storytelling'],['دعم إنتاج البودكاست','مشاركة الشباب','صناعة الحكاية']]},
  {id:'mashloom',category:'creative',stage:'completed',title:['Al Mashloom · المشلوم','المشلوم'],status:['Published','منشور'],
    role:['Independent work / Author','عمل مستقل / تأليف'],
    description:['A published, printed book by Nabil. A different expression of the same creative instinct: turning a personal voice into something people can hold, read and connect with.','كتاب منشور ومطبوع من تأليف نبيل. تعبير مختلف عن الدافع الإبداعي ذاته: تحويل صوت شخصي إلى عمل يمكن للناس اقتناؤه وقراءته والتفاعل معه.'],
    tags:[['Writing','Independent publishing','Personal voice'],['الكتابة','النشر المستقل','الصوت الشخصي']]},
  {id:'square',category:'creative',stage:'exploration',title:['Abu Ras Murabba3','أبو راس مربع'],status:['Campaign concept','فكرة حملة'],
    role:['Creative concept / Behaviour-change communication','فكرة إبداعية / التواصل لتغيير السلوك'],
    description:['A campaign concept using a square-headed character to make everyday behaviours visible and start a conversation. A memorable character carrying a message without becoming a lecture.','فكرة حملة تستخدم شخصية برأس مربّع لتسليط الضوء على سلوكيات يومية وفتح النقاش حولها. شخصية لافتة تحمل الرسالة دون أن تتحول إلى موعظة.'],
    tags:[['Character concept','Behaviour change','Campaign strategy'],['ابتكار الشخصيات','تغيير السلوك','استراتيجية الحملات']]},
  {id:'anti-narcotics',category:'creative',stage:'archive',title:['Anti-narcotics · Awareness content','مكافحة المخدرات · محتوى توعوي'],status:['Creative collaboration','تعاون إبداعي'],
    role:['Campaign promotion & bilingual video copy','الترويج للحملات وكتابة محتوى الفيديو باللغتين'],
    description:['Awareness content with Jordan’s Anti-Narcotics Department, including a promotional reel for its public creative competition and Arabic–English video copy and subtitles.','محتوى توعوي بالتعاون مع مكافحة المخدرات في الأردن، يشمل ريلًا ترويجيًا لمسابقتها الإبداعية المفتوحة للجمهور، وكتابة نصوص الفيديو وإعداد الترجمة بالعربية والإنجليزية.'],
    tags:[['Public awareness','Short-form video','Bilingual content'],['التوعية المجتمعية','الفيديو القصير','محتوى باللغتين']]},
  {id:'four-by-four',category:'creative',stage:'archive',title:['4×4 Club','نادي الدفع الرباعي'],status:['Creative collaboration','تعاون إبداعي'],
    role:['Creative communications / Collaboration','التواصل الإبداعي / تعاون'],
    description:['A collaboration with the 4×4 Club, part of Nabil’s creative communications work.','تعاون مع نادي الدفع الرباعي ضمن أعمال نبيل في التواصل الإبداعي.'],
    tags:[['Creative communications','Collaboration'],['التواصل الإبداعي','تعاون']]}
];

const profile = {
  en:{
    navWork:'The work',workLabel:'02 / THE WORK, IN MOTION',workTitle:'Built to work.<br><em>Made to matter.</em>',
    workIntro:'Explore digital products, campaigns and independent work. Each project shows its scope and current stage.',
    provenance:'This portfolio brings together Studio Irth projects, independent work, collaborations and professional experience. UNICEF work is credited in its original context. Prototypes and concepts are labelled; project-cover graphics are editorial interpretations.',
    statusAll:'Every stage',statusActive:'In progress',statusDone:'Delivered & published',statusIdeas:'Concepts & prototypes',statusArchive:'Experience & collaborations',
    indexLabel:'THE PROJECT INDEX',indexHint:'Open a project to explore the work.',empty:'No projects match these filters.',results:'projects in view',read:'Explore the project',contribution:'The work behind it',
    aboutTitle:'A systems mind.<br><em>A storyteller’s instinct.</em>',
    bio1:'I’m Nabil Aref—founder of Studio Irth, a technology specialist, business analyst and storyteller based in Amman. I’m interested in the space between how things work and how they make people feel.',
    bio2:'My work moves from humanitarian technology and everyday business systems to campaigns, books and conversations on screen. I founded ADHDJO to make space for honest Arabic conversations about ADHD and neurodiversity. Irth brings these worlds together: practical thinking, creative expression and a reason to care.',
    skillsLink:'Explore my skills',mediaLink:'Watch my appearances',personalNote:'BUILDER. STORYTELLER. CONNECTOR.',skillsLabel:'WHAT I BRING TO THE TABLE',skillsTitle:'One person.<br>Many ways to connect.',
    skillGroups:[
      ['01','Systems & solutions','I turn messy processes into something people can use.',['Business analysis & requirements','Process and workflow design','Power Apps, Power Automate & SharePoint','Power BI, reporting & dashboards','Application and website prototyping','Network & device management']],
      ['02','Strategy & storytelling','I find the human angle inside a complicated idea.',['Audience insight & messaging','Campaign concepts & creative direction','Arabic & English copywriting','Scripts, reels & story development','Behaviour-change communication','Community building']],
      ['03','Production & people','I help ideas travel from the room to the audience.',['Video, photography & content creation','Podcast & audio production support','On-camera storytelling & public speaking','Facilitation & youth engagement','Stakeholder and partner coordination','Creative and technical collaboration']]
    ],
    mediaLabel:'ON AIR / IN CONVERSATION',mediaTitle:'A voice beyond<br><em>the feed.</em>',mediaIntro:'Television features, workshops and long-form conversations.',watch:'Watch the conversation',mediaNote:'Speaking from lived experience. These appearances form part of Nabil’s personal media work.',
    media:[
      ['Television · 2024','BBC News Arabic','How ADHD shapes young lives','A BBC Xtra TV feature following Nabil’s experience and his journey into awareness content.'],
      ['Workshop','Ahli Bank Workshop','In conversation at Ahli Bank','Nabil’s participation in a workshop at Ahli Bank.'],
      ['Podcast · 2024','Warsheh Podcast','Could everyone have ADHD?','An extended Arabic conversation about lived experience, diagnosis and learning to understand yourself.']
    ]
  },
  ar:{
    navWork:'الأعمال',workLabel:'02 / أعمال تتحرك وتتطوّر',workTitle:'حلول تعمل.<br><em>وحكايات تترك أثرًا.</em>',
    workIntro:'اكتشف المنتجات الرقمية والحملات والأعمال المستقلة، مع نطاق كل مشروع والمرحلة التي وصل إليها.',
    provenance:'يجمع الملف مشاريع استوديو إرث والأعمال المستقلة والتعاونات والخبرة المهنية. تُنسب أعمال اليونيسف إلى سياقها الأصلي. النماذج الأولية والأفكار موضّحة، ورسومات أغلفة المشاريع تعبيرات تصميمية عنها.',
    statusAll:'كل المراحل',statusActive:'قيد العمل',statusDone:'منفّذ ومنشور',statusIdeas:'أفكار ونماذج أولية',statusArchive:'خبرات وتعاونات',
    indexLabel:'فهرس المشاريع',indexHint:'افتح المشروع لتكتشف تفاصيله.',empty:'لا توجد مشاريع تطابق هذه الخيارات.',results:'مشاريع معروضة',read:'اكتشف المشروع',contribution:'خلف العمل',
    aboutTitle:'عقل يبني الأنظمة.<br><em>وروح تروي الحكايات.</em>',
    bio1:'أنا نبيل عارف، مؤسس استوديو إرث، ومتخصص في التقنية، ومحلل أعمال، وحكّاء من عمّان. تشدّني المساحة بين طريقة عمل الأشياء وما تتركه في الناس.',
    bio2:'يمتد عملي من التقنية في المجال الإنساني وأنظمة الأعمال اليومية، إلى الحملات والكتب والحوارات أمام الكاميرا. أسست ADHDJO لفتح مساحة عربية صادقة للحديث عن اضطراب فرط الحركة وتشتّت الانتباه والتنوّع العصبي. يجمع إرث هذه العوالم: تفكير عملي، وتعبير إبداعي، وسبب يجعلنا نهتم.',
    skillsLink:'اكتشف مهاراتي',mediaLink:'شاهد مشاركاتي الإعلامية',personalNote:'أبني. أحكي. وأصل الأفكار بالناس.',skillsLabel:'ما أضيفه إلى العمل',skillsTitle:'شخص واحد.<br>وطرق كثيرة للتواصل.',
    skillGroups:[
      ['01','الأنظمة والحلول','أحوّل الإجراءات المتشابكة إلى أدوات يستطيع الناس استخدامها.',['تحليل الأعمال وجمع المتطلبات','تصميم العمليات ومسارات العمل','<bdi lang="en" dir="ltr">Power Apps</bdi> و<bdi lang="en" dir="ltr">Power Automate</bdi> و<bdi lang="en" dir="ltr">SharePoint</bdi>','<bdi lang="en" dir="ltr">Power BI</bdi> والتقارير ولوحات البيانات','نمذجة التطبيقات والمواقع','إدارة الشبكات والأجهزة']],
      ['02','الاستراتيجية والحكاية','أبحث عن الزاوية الإنسانية داخل الفكرة المعقّدة.',['فهم الجمهور وصياغة الرسائل','أفكار الحملات والتوجيه الإبداعي','الكتابة بالعربية والإنجليزية','السيناريو والريلز وتطوير الحكاية','التواصل لتغيير السلوك','بناء المجتمعات']],
      ['03','الإنتاج والعمل مع الناس','أساعد الأفكار على الوصول من غرفة العمل إلى الجمهور.',['الفيديو والتصوير وصناعة المحتوى','دعم إنتاج البودكاست والصوت','السرد أمام الكاميرا والتحدث للجمهور','التيسير ومشاركة الشباب','التنسيق مع الشركاء وأصحاب المصلحة','التعاون الإبداعي والتقني']]
    ],
    mediaLabel:'على الشاشة / في الحوار',mediaTitle:'صوت يتجاوز<br><em>حدود المنشور.</em>',mediaIntro:'ظهور تلفزيوني وورش عمل وحوارات مطوّلة.',watch:'شاهد الحوار',mediaNote:'حديث من واقع التجربة الشخصية. هذه المشاركات جزء من الحضور الإعلامي لنبيل.',
    media:[
      ['تلفزيون · ٢٠٢٤','BBC News عربي','كيف يؤثر ADHD على حياة الشباب؟','تقرير لبرنامج بي بي سي إكسترا يتابع تجربة نبيل وانتقاله إلى صناعة المحتوى التوعوي.'],
      ['ورشة عمل','ورشة البنك الأهلي','في حوار لدى البنك الأهلي','مشاركة نبيل في ورشة عمل لدى البنك الأهلي.'],
      ['بودكاست · ٢٠٢٤','بودكاست ورشة','معقول كل الناس ADHD؟','حوار مطوّل بالعربية عن التجربة الشخصية والتشخيص ورحلة فهم الذات.']
    ]
  }
};
for (const language of ['en','ar']) Object.assign(copy[language],profile[language]);
const mediaLinks=['https://www.youtube.com/watch?v=OkTa1sZfhpY','https://www.youtube.com/watch?v=zDppZQAVnWY&t=347s','https://www.youtube.com/watch?v=PWRzpfD7-vo'];
